- name: MarkdownLint mdl Action
  uses: actionshub/markdownlint@1.2.2
  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
